name: introduction_card1
description: Automation app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  webview_flutter: ^2.1.2
  mqtt_client: ^7.2.1

  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Hero
      fonts:
        - asset: assets/fonts/Hero-Regular.ttf
        - asset: assets/fonts/Hero-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
